name: springboot project
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: {{secrets.DOCKER_USERNAME}}
          password: {{secrets.DOCKER_ACCESS_TOKEN}}
