name: springboot project
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}
      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build Push docker image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
            context: ./
            file: ./Dockerfile
            builder: ${{steps.buildx.ouputs.name}}
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/springboot-project
      - name: Verify
        run: echo ${{steps.docker_build.ouputs.digest}}